name: Pull request

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    name: Sonar analisis
    runs-on: sonarqube
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
      env:
        DOTNET_INSTALL_DIR: ${{ runner.temp }}/dotnet
        DOTNET_ROOT: ${{ runner.temp }}/dotnet
    
    - name: Añadir dotnet al PATH
      run: echo "${{ runner.temp }}/dotnet" >> $GITHUB_PATH
    
    - name: Restaurar dependencias
      run: dotnet restore poc.Csharp.csproj

    - name: SonarQube - Install dotnet-sonarscanner
      run: dotnet tool install --global dotnet-sonarscanner --version 5.12.0

    - name: SonarQube - Begin analysis
      env:
        DOTNET_ROOT: ${{ runner.temp }}/dotnet
      run: |
        export PATH="${{ runner.temp }}/dotnet:$HOME/.dotnet/tools:$PATH"
        dotnet sonarscanner begin \
          /k:"Inetum_MiBanco_POC-csharp" \
          /n:"POC-csharp" \
          /d:sonar.host.url="http://192.168.2.184:9000" \
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.cs.opencover.reportsPaths="**/TestResults/*/coverage.opencover.xml" \
          /d:sonar.sourceEncoding="utf-8"

    - name: Build
      run: dotnet build poc.Csharp.csproj --configuration Release

    - name: Test + generar cobertura (OpenCover via coverlet)
      run: |
        dotnet test poc.Csharp.csproj --configuration Release --no-build \
          /p:CollectCoverage=true \
          /p:CoverletOutput=TestResults/ \
          /p:CoverletOutputFormat=opencover

    - name: SonarQube - End analysis
      run: |
        export PATH="$PATH:$HOME/.dotnet/tools"
        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
